### ISSUE TITLE
When renaming a checklist with unsaved item(s), the "Discard Text?" pop up message will appear more than once when choosing to cancel changes.

### ISSUE THREAD

**Issue by saadnaji** [mikeberger/borg_calendar#29]
##### Problem description:
When attempting to rename a checklist with unsaved item(s) it will causes the "Discard text?" pop up message to appear multiple times when the user chooses to cancel the discarded changes. Not only that, it will cause the other checklists to temporarily disappear while performing canceling operation. Moreover, the more stored checklists the user have, the greater number of "Discard text?" pop up message will appear. The issue only appears when running BORG on Linux environment.

##### Note
This issue is only present when using OpenJDK version 7. Since this is not reported on this page
http://mbcsoft.com/joomla30/index.php/borg/12-linux-peculiarities
It is good to update the issues list on Linux system
##### Environment and Setup: 
Hardware: Clevo Laptop
JDK version: OpenJDK Java 7 development kit
Java version: 1.7.0_75
CUPS version: 2.0.1-1
System type: 64-bit
OS:  ArchLinux
BORGCalendar Version: 1.8.1

##### How to reproduce the issue: 
1. Create a new checklist. 

        * For example, list 1
2. Add item to newly created checklist and do not click on 'Save checklist'. 

        * add item 1 to list 1
3. Rename the new created list to a different name by performing right-click-> rename.

        * Rename list 1 to list 2
4. A pop up "Discard Text?" message will appear.
5. Click on "'Cancel". However, the pop up message will appear more than once.
6. Click on "Cancel" many times to remove the pop up message.
7. This will also caused the checklists to disappear and reapperar as you press "Cancel" button.

##### Suggestion for Fix: 
1. "Discard text?" pop up message should not appear after choosing to press cancel.
2. If there is more than one checklist, they should not disappear when choosing to cancel option on "Discard text?" pop up message.

**Comment by mikeberger** [comment]
I can't reproduce on linux with either OpenJDK or oracle JRE. However, when trying this and then allowing the rename, no further checklist editing works and I get the stack trace below. So, there is a bug of some sort - may all be the same thing. Needs investigation.


Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 3
        at net.sf.borg.ui.util.TableSorter.modelIndex(TableSorter.java:248)
        at net.sf.borg.ui.util.TableSorter.setValueAt(TableSorter.java:296)
        at javax.swing.JTable.setValueAt(JTable.java:2741)
        at javax.swing.JTable.editingStopped(JTable.java:4723)
        at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141)
        at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368)
        at javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:233)
        at javax.swing.JTable$GenericEditor.stopCellEditing(JTable.java:5467)
        at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1010)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
        at java.awt.Component.processMouseEvent(Component.java:6522)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2739)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:702)
        at java.awt.EventQueue$3.run(EventQueue.java:696)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:724)
        at java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
