### ISSUE TITLE
Running Borg under Ubuntu 15.10

### ISSUE THREAD

**Issue by david-burleigh** [mikeberger/borg_calendar#59]
I ran the borg_installer-1.8.1.jar, but when I try to start up the program, I get:

zerubbabel@dz:~/bin/Borg$ ./run_borg.sh
: No such file or directory/home/zerubbabel/bin/Borg
Nov 01, 2015 12:15:16 PM net.sf.borg.common.SocketClient sendMsg
INFO: Connection closed by server.
zerubbabel@dz:~/bin/Borg$

Where do I go from here?

**Comment by mikeberger** [comment]
check the contents of ~/.borg.log and ~/.borg.out
there might be errors in the log files

**Comment by david-burleigh** [comment]
Here's another try after a reboot:

zerubbabel@dz:~/bin/Borg$ ./run_borg.sh
: No such file or directory/home/zerubbabel/bin/Borg
^C [it hung at this point]
zerubbabel@dz:~/bin/Borg$ 

Contents of .borg.log:
Nov 01, 2015 3:14:50 PM net.sf.borg.model.db.jdbc.JdbcDB buildDbDir
INFO: DB URL is: jdbc:h2:file:/home/zerubbabel/.borg_db/borgdb;USER=sa
Nov 01, 2015 3:14:52 PM net.sf.borg.common.SocketServer <init>
INFO: Server: listening on port 2929

Contents of .borg.out:
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.jgoodies.looks.plastic.PlasticLookAndFeel.<clinit>(PlasticLookAndFeel.java:135)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:1872)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
	at net.sf.borg.ui.UIControl.startUI(UIControl.java:110)
	at net.sf.borg.control.Borg$5.run(Borg.java:490)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.awt.HeadlessException
	at sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:224)
	at com.jgoodies.looks.LookUtils.isLowResolution(LookUtils.java:480)
	at com.jgoodies.looks.LookUtils.<clinit>(LookUtils.java:249)
	... 21 more

**Comment by mikeberger** [comment]
Did you mean to close this issue? 

The exception is coming from the JGoodies looks look and feel library, which is pretty old software. Perhaps you can cd to the lib folder and: "mv looks-2.2.2.jar .." to move that library out of the way. then try to start the program and see if it works. It should try to start with the default java look and feel.

Can you send the output of "java -version" so I can see what version of java you have?

I cannot duplicate your problem on unbuntu 14.04 with OpenJdk 1.7. that's my most up to date linux box at the moment. I might need to install ubuntu 15.10 into a VM to duplicate your problem.

**Comment by david-burleigh** [comment]
No, I didn't intend to close it. Here's the Java version info:
zerubbabel@dz:~/bin/Borg$ java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
zerubbabel@dz:~/bin/Borg$

**Comment by david-burleigh** [comment]
After moving looks-2.2.2.jar, .borg.log shows:
Nov 01, 2015 3:39:14 PM net.sf.borg.model.db.jdbc.JdbcDB buildDbDir
INFO: DB URL is: jdbc:h2:file:/home/zerubbabel/.borg_db/borgdb;USER=sa
Nov 01, 2015 3:39:14 PM net.sf.borg.common.SocketServer <init>
INFO: Server: listening on port 2929
Nov 01, 2015 3:39:14 PM net.sf.borg.ui.UIControl startUI
SEVERE: java.lang.ClassNotFoundException: com.jgoodies.looks.plastic.PlasticXPLookAndFeel

**Comment by david-burleigh** [comment]
And .borg.out has:
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1756)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1831)
	at javax.swing.JDialog.<init>(JDialog.java:270)
	at javax.swing.JDialog.<init>(JDialog.java:204)
	at javax.swing.JDialog.<init>(JDialog.java:152)
	at net.sf.borg.ui.util.SplashScreen.<init>(SplashScreen.java:58)
	at net.sf.borg.ui.UIControl.startUI(UIControl.java:119)
	at net.sf.borg.control.Borg$5.run(Borg.java:490)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by mikeberger** [comment]
ok. I was able to reproduce this on ubuntu 14.04 by uninstalling the default-jre, leaving only the headless jre. I suspect that you only have the headless version of java installed. that is strange.
In case you aren't familiar with that, ubuntu lets you install a headless version of java that can't run graphical programs and is optimized for server-only use.

On ubuntu 14.04, I was able to install the full version of java with 
sudo apt-get install default-jre

Perhaps that will fix it for you.

If that works, you can move the looks jar back into the lib directory as I think that looks makes the program look better than the default.

**Comment by david-burleigh** [comment]
Yes, that worked. Thank you very much!
